services:
  invoices_pg:
    image: bitnami/postgresql:latest
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=invoices
      - POSTGRES_PASSWORD=invoices
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
