services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
